In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../../data/processed_data/full_df.csv")
df.head()

,Unnamed: 0,Unnamed: 0.1,State FIPS Code,County FIPS Code,5-digit FIPS Code,State Abbreviation,Name,Release Year,County Ranked (Yes=1/No=0),Premature death raw value,...,March Average Precipitation,April Average Precipitation,May Average Precipitation,June Average Precipitation,July Average Precipitation,August Average Precipitation,September Average Precipitation,October Average Precipitation,November Average Precipitation,December Average Precipitation
0,0,0,1,1,1001,AL,Autauga County,2010,1.0,9778.1,...,5.26,2.17,5.72,2.47,3.38,4.38,1.38,3.14,5.01,1.89
1,1,1,1,3,1003,AL,Baldwin County,2010,1.0,8221.7,...,4.77,2.31,6.31,4.94,4.08,9.38,2.24,2.06,6.11,2.19
2,2,2,1,9,1009,AL,Blount County,2010,1.0,8929.7,...,6.76,5.66,7.47,3.39,3.55,4.31,1.23,3.12,4.62,2.07
3,3,3,1,15,1015,AL,Calhoun County,2010,1.0,11526.2,...,6.10,3.73,6.46,2.70,4.00,3.78,1.55,2.96,3.06,2.24
4,4,4,1,31,1031,AL,Coffee County,2010,1.0,9004.7,...,3.46,1.88,4.71,3.84,2.78,6.30,2.41,1.38,3.71,2.03

In [3]:
df = df.drop(['Unnamed: 0', 'Unnamed: 0.1'], axis=1)
df.head()

,State FIPS Code,County FIPS Code,5-digit FIPS Code,State Abbreviation,Name,Release Year,County Ranked (Yes=1/No=0),Premature death raw value,Premature death numerator,Premature death denominator,...,March Average Precipitation,April Average Precipitation,May Average Precipitation,June Average Precipitation,July Average Precipitation,August Average Precipitation,September Average Precipitation,October Average Precipitation,November Average Precipitation,December Average Precipitation
0,1,1,1001,AL,Autauga County,2010,1.0,9778.1,670.0,137881.0,...,5.26,2.17,5.72,2.47,3.38,4.38,1.38,3.14,5.01,1.89
1,1,3,1003,AL,Baldwin County,2010,1.0,8221.7,2148.0,449589.0,...,4.77,2.31,6.31,4.94,4.08,9.38,2.24,2.06,6.11,2.19
2,1,9,1009,AL,Blount County,2010,1.0,8929.7,787.0,155580.0,...,6.76,5.66,7.47,3.39,3.55,4.31,1.23,3.12,4.62,2.07
3,1,15,1015,AL,Calhoun County,2010,1.0,11526.2,2035.0,313874.0,...,6.10,3.73,6.46,2.70,4.00,3.78,1.55,2.96,3.06,2.24
4,1,31,1031,AL,Coffee County,2010,1.0,9004.7,645.0,126516.0,...,3.46,1.88,4.71,3.84,2.78,6.30,2.41,1.38,3.71,2.03

In [4]:
rucc_df = pd.read_excel('../../data/county_level/urbanization_codes/rucc2013.xls')
rucc_df.head()

,FIPS,State,County_Name,Population_2010,RUCC_2013,Description
0,1001,AL,Autauga County,54571,2.0,"Metro - Counties in metro areas of 250,000 to ..."
1,1003,AL,Baldwin County,182265,3.0,Metro - Counties in metro areas of fewer than ...
2,1005,AL,Barbour County,27457,6.0,"Nonmetro - Urban population of 2,500 to 19,999..."
3,1007,AL,Bibb County,22915,1.0,Metro - Counties in metro areas of 1 million p...
4,1009,AL,Blount County,57322,1.0,Metro - Counties in metro areas of 1 million p...

In [5]:
rucc_df['FIPS'] = rucc_df['FIPS'].astype('str').apply(lambda fips: "0" + fips if len(fips) == 4 else fips)
rucc_df.head()

,FIPS,State,County_Name,Population_2010,RUCC_2013,Description
0,01001,AL,Autauga County,54571,2.0,"Metro - Counties in metro areas of 250,000 to ..."
1,01003,AL,Baldwin County,182265,3.0,Metro - Counties in metro areas of fewer than ...
2,01005,AL,Barbour County,27457,6.0,"Nonmetro - Urban population of 2,500 to 19,999..."
3,01007,AL,Bibb County,22915,1.0,Metro - Counties in metro areas of 1 million p...
4,01009,AL,Blount County,57322,1.0,Metro - Counties in metro areas of 1 million p...

In [6]:
rucc_df.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3234 entries, 0 to 3233
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   FIPS             3234 non-null   object
 1   State            3234 non-null   object
 2   County_Name      3234 non-null   object
 3   Population_2010  3234 non-null   int64
 4   RUCC_2013        3232 non-null   float64
 5   Description      3234 non-null   object
dtypes: float64(1), int64(1), object(4)
memory usage: 151.7+ KB

In [8]:
df['5-digit FIPS Code'] = df['5-digit FIPS Code'].astype('str').apply(lambda fips: "0" + fips if len(fips) == 4 else fips)
df.head()

,State FIPS Code,County FIPS Code,5-digit FIPS Code,State Abbreviation,Name,Release Year,County Ranked (Yes=1/No=0),Premature death raw value,Premature death numerator,Premature death denominator,...,March Average Precipitation,April Average Precipitation,May Average Precipitation,June Average Precipitation,July Average Precipitation,August Average Precipitation,September Average Precipitation,October Average Precipitation,November Average Precipitation,December Average Precipitation
0,1,1,01001,AL,Autauga County,2010,1.0,9778.1,670.0,137881.0,...,5.26,2.17,5.72,2.47,3.38,4.38,1.38,3.14,5.01,1.89
1,1,3,01003,AL,Baldwin County,2010,1.0,8221.7,2148.0,449589.0,...,4.77,2.31,6.31,4.94,4.08,9.38,2.24,2.06,6.11,2.19
2,1,9,01009,AL,Blount County,2010,1.0,8929.7,787.0,155580.0,...,6.76,5.66,7.47,3.39,3.55,4.31,1.23,3.12,4.62,2.07
3,1,15,01015,AL,Calhoun County,2010,1.0,11526.2,2035.0,313874.0,...,6.10,3.73,6.46,2.70,4.00,3.78,1.55,2.96,3.06,2.24
4,1,31,01031,AL,Coffee County,2010,1.0,9004.7,645.0,126516.0,...,3.46,1.88,4.71,3.84,2.78,6.30,2.41,1.38,3.71,2.03

In [9]:
# Create dict of county FIPS codes to 2013 RUCC code for quick access
rucc_dict = dict(zip(rucc_df.FIPS, rucc_df.RUCC_2013))

In [10]:
def compute_rucc_code(row):
    rucc_2013 = rucc_dict[row['5-digit FIPS Code']]
    return rucc_2013
    """
    pop = row['Population']
    if row['Release Year'] == 2013:
        return rucc_2013
    elif rucc_2013 <= 3: # Metropolitan counties
        if pop >= 1000000:
            return 1.0
        elif pop >= 250000:
            return 2.0
        else:
            return 3.0
    elif rucc_2013 in {4.0, 6.0, 8.0}: # Nonmetroplitan counties adjacent to metro areas
        if pop >= 20000:
            return 4.0
        elif pop >= 2500:
            return 6.0
        else:
            return 8.0
    else: # Nonmetropolitan counties not adjacent to metro areas
        if pop >= 20000:
            return 5.0
        elif pop >= 2500:
            return 7.0
        else:
            return 9.0
    """

In [11]:
df['RUCC'] = df.apply(compute_rucc_code, axis=1)
df.head()

,State FIPS Code,County FIPS Code,5-digit FIPS Code,State Abbreviation,Name,Release Year,County Ranked (Yes=1/No=0),Premature death raw value,Premature death numerator,Premature death denominator,...,April Average Precipitation,May Average Precipitation,June Average Precipitation,July Average Precipitation,August Average Precipitation,September Average Precipitation,October Average Precipitation,November Average Precipitation,December Average Precipitation,RUCC
0,1,1,01001,AL,Autauga County,2010,1.0,9778.1,670.0,137881.0,...,2.17,5.72,2.47,3.38,4.38,1.38,3.14,5.01,1.89,2.0
1,1,3,01003,AL,Baldwin County,2010,1.0,8221.7,2148.0,449589.0,...,2.31,6.31,4.94,4.08,9.38,2.24,2.06,6.11,2.19,3.0
2,1,9,01009,AL,Blount County,2010,1.0,8929.7,787.0,155580.0,...,5.66,7.47,3.39,3.55,4.31,1.23,3.12,4.62,2.07,1.0
3,1,15,01015,AL,Calhoun County,2010,1.0,11526.2,2035.0,313874.0,...,3.73,6.46,2.70,4.00,3.78,1.55,2.96,3.06,2.24,3.0
4,1,31,01031,AL,Coffee County,2010,1.0,9004.7,645.0,126516.0,...,1.88,4.71,3.84,2.78,6.30,2.41,1.38,3.71,2.03,4.0

In [12]:
df.groupby(['5-digit FIPS Code', 'State Abbreviation', 'Name']).Population.apply(list).reset_index() # list of population values for each county

,5-digit FIPS Code,State Abbreviation,Name,Population
0,01001,AL,Autauga County,"[54571, 55255, 55027, 54792, 55416]"
1,01003,AL,Baldwin County,"[182265, 186653, 190403, 195147, 199745, 20369..."
2,01009,AL,Blount County,"[57322, 57772, 57676, 57704]"
3,01015,AL,Calhoun County,"[118572, 117736, 117208, 116475, 115837, 11528..."
4,01017,AL,Chambers County,[33843]
...,...,...,...,...
1280,56021,WY,Laramie County,"[91738, 92637, 94785, 95929, 96264, 97183, 98136]"
1281,56025,WY,Natrona County,"[75450, 76410, 78602, 81092, 81432, 82191, 81039]"
1282,56029,WY,Park County,"[28839, 29096, 29056, 29353]"
1283,56033,WY,Sheridan County,"[29580, 29777, 29994, 30069]"
1284,56037,WY,Sweetwater County,"[43806, 44028, 45086, 45144, 44693]"

In [13]:
df.groupby(['5-digit FIPS Code', 'State Abbreviation', 'Name']).RUCC.apply(list).reset_index() # list of corresponding computed RUCC values for each county

,5-digit FIPS Code,State Abbreviation,Name,RUCC
0,01001,AL,Autauga County,"[2.0, 2.0, 2.0, 2.0, 2.0]"
1,01003,AL,Baldwin County,"[3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0]"
2,01009,AL,Blount County,"[1.0, 1.0, 1.0, 1.0]"
3,01015,AL,Calhoun County,"[3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0]"
4,01017,AL,Chambers County,[6.0]
...,...,...,...,...
1280,56021,WY,Laramie County,"[3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0]"
1281,56025,WY,Natrona County,"[3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0]"
1282,56029,WY,Park County,"[7.0, 7.0, 7.0, 7.0]"
1283,56033,WY,Sheridan County,"[7.0, 7.0, 7.0, 7.0]"
1284,56037,WY,Sweetwater County,"[5.0, 5.0, 5.0, 5.0, 5.0]"

In [14]:
df.groupby(['5-digit FIPS Code', 'State Abbreviation', 'Name'])['Release Year'].apply(list).reset_index() # list of corresponding computed RUCC values for each county

,5-digit FIPS Code,State Abbreviation,Name,Release Year
0,01001,AL,Autauga County,"[2010, 2011, 2012, 2013, 2016]"
1,01003,AL,Baldwin County,"[2010, 2011, 2012, 2013, 2014, 2015, 2016]"
2,01009,AL,Blount County,"[2010, 2012, 2015, 2016]"
3,01015,AL,Calhoun County,"[2010, 2011, 2012, 2013, 2014, 2015, 2016]"
4,01017,AL,Chambers County,[2016]
...,...,...,...,...
1280,56021,WY,Laramie County,"[2010, 2011, 2012, 2013, 2014, 2015, 2016]"
1281,56025,WY,Natrona County,"[2010, 2011, 2012, 2013, 2014, 2015, 2016]"
1282,56029,WY,Park County,"[2012, 2013, 2015, 2016]"
1283,56033,WY,Sheridan County,"[2012, 2013, 2014, 2015]"
1284,56037,WY,Sweetwater County,"[2010, 2011, 2012, 2013, 2015]"

In [15]:
df

,State FIPS Code,County FIPS Code,5-digit FIPS Code,State Abbreviation,Name,Release Year,County Ranked (Yes=1/No=0),Premature death raw value,Premature death numerator,Premature death denominator,...,April Average Precipitation,May Average Precipitation,June Average Precipitation,July Average Precipitation,August Average Precipitation,September Average Precipitation,October Average Precipitation,November Average Precipitation,December Average Precipitation,RUCC
0,1,1,01001,AL,Autauga County,2010,1.0,9778.1,670.0,137881.0,...,2.17,5.72,2.47,3.38,4.38,1.38,3.14,5.01,1.89,2.0
1,1,3,01003,AL,Baldwin County,2010,1.0,8221.7,2148.0,449589.0,...,2.31,6.31,4.94,4.08,9.38,2.24,2.06,6.11,2.19,3.0
2,1,9,01009,AL,Blount County,2010,1.0,8929.7,787.0,155580.0,...,5.66,7.47,3.39,3.55,4.31,1.23,3.12,4.62,2.07,1.0
3,1,15,01015,AL,Calhoun County,2010,1.0,11526.2,2035.0,313874.0,...,3.73,6.46,2.70,4.00,3.78,1.55,2.96,3.06,2.24,3.0
4,1,31,01031,AL,Coffee County,2010,1.0,9004.7,645.0,126516.0,...,1.88,4.71,3.84,2.78,6.30,2.41,1.38,3.71,2.03,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6275,56,1,56001,WY,Albany County,2016,1.0,5297.8,258.0,107325.0,...,2.93,2.46,0.89,0.39,0.63,0.80,0.32,0.91,1.18,4.0
6276,56,13,56013,WY,Fremont County,2016,1.0,13137.7,679.0,114673.0,...,2.96,3.32,0.49,0.25,0.77,2.27,1.92,0.85,2.04,7.0
6277,56,21,56021,WY,Laramie County,2016,1.0,7002.7,1029.0,266542.0,...,3.61,2.42,1.16,1.02,1.51,0.82,0.30,0.54,0.72,3.0
6278,56,25,56025,WY,Natrona County,2016,1.0,8170.3,957.0,222066.0,...,2.72,2.25,0.64,0.49,0.87,1.61,0.53,0.57,0.87,3.0
6279,56,29,56029,WY,Park County,2016,1.0,6333.2,334.0,79665.0,...,2.39,2.28,0.76,1.05,0.79,2.21,4.32,1.34,3.68,7.0

In [16]:
df.to_csv("../../data/processed_data/full_df.csv", index=False)

In [17]:
pd.read_csv("../../data/processed_data/full_df.csv") # check that it saved correctly

,State FIPS Code,County FIPS Code,5-digit FIPS Code,State Abbreviation,Name,Release Year,County Ranked (Yes=1/No=0),Premature death raw value,Premature death numerator,Premature death denominator,...,April Average Precipitation,May Average Precipitation,June Average Precipitation,July Average Precipitation,August Average Precipitation,September Average Precipitation,October Average Precipitation,November Average Precipitation,December Average Precipitation,RUCC
0,1,1,1001,AL,Autauga County,2010,1.0,9778.1,670.0,137881.0,...,2.17,5.72,2.47,3.38,4.38,1.38,3.14,5.01,1.89,2.0
1,1,3,1003,AL,Baldwin County,2010,1.0,8221.7,2148.0,449589.0,...,2.31,6.31,4.94,4.08,9.38,2.24,2.06,6.11,2.19,3.0
2,1,9,1009,AL,Blount County,2010,1.0,8929.7,787.0,155580.0,...,5.66,7.47,3.39,3.55,4.31,1.23,3.12,4.62,2.07,1.0
3,1,15,1015,AL,Calhoun County,2010,1.0,11526.2,2035.0,313874.0,...,3.73,6.46,2.70,4.00,3.78,1.55,2.96,3.06,2.24,3.0
4,1,31,1031,AL,Coffee County,2010,1.0,9004.7,645.0,126516.0,...,1.88,4.71,3.84,2.78,6.30,2.41,1.38,3.71,2.03,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6275,56,1,56001,WY,Albany County,2016,1.0,5297.8,258.0,107325.0,...,2.93,2.46,0.89,0.39,0.63,0.80,0.32,0.91,1.18,4.0
6276,56,13,56013,WY,Fremont County,2016,1.0,13137.7,679.0,114673.0,...,2.96,3.32,0.49,0.25,0.77,2.27,1.92,0.85,2.04,7.0
6277,56,21,56021,WY,Laramie County,2016,1.0,7002.7,1029.0,266542.0,...,3.61,2.42,1.16,1.02,1.51,0.82,0.30,0.54,0.72,3.0
6278,56,25,56025,WY,Natrona County,2016,1.0,8170.3,957.0,222066.0,...,2.72,2.25,0.64,0.49,0.87,1.61,0.53,0.57,0.87,3.0
6279,56,29,56029,WY,Park County,2016,1.0,6333.2,334.0,79665.0,...,2.39,2.28,0.76,1.05,0.79,2.21,4.32,1.34,3.68,7.0